import {
  Activity,
  ArrowLeftRight,
  Gauge,
  LayoutDashboard,
  Network,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  UserRound,
  Users,
} from "lucide-react";

export const navigation = [
  {
    path: "/dashboard",
    title: "仪表盘",
    description: "查看流量用量、隧道权限与网络概况。",
    group: "工作空间",
    icon: LayoutDashboard,
  },
  {
    path: "/monitor",
    title: "运行监控",
    description: "跟踪节点资源、服务可用性与隧道质量。",
    group: "工作空间",
    icon: Activity,
  },
  {
    path: "/forward",
    title: "转发规则",
    description: "管理入口端口、目标地址与流量转发策略。",
    group: "网络服务",
    icon: ArrowLeftRight,
  },
  {
    path: "/tunnel",
    title: "隧道管理",
    description: "配置入口、中继与出口，组织转发链路。",
    group: "网络服务",
    icon: Network,
    adminOnly: true,
  },
  {
    path: "/node",
    title: "节点管理",
    description: "管理本地与远程节点，查看连接和部署状态。",
    group: "网络服务",
    icon: Server,
    adminOnly: true,
  },
  {
    path: "/user",
    title: "用户管理",
    description: "管理用户配额、隧道访问和监控权限。",
    group: "访问与管理",
    icon: Users,
    adminOnly: true,
  },
  {
    path: "/group",
    title: "分组权限",
    description: "通过用户组与隧道组统一分配访问权限。",
    group: "访问与管理",
    icon: ShieldCheck,
    adminOnly: true,
  },
  {
    path: "/limit",
    title: "限速策略",
    description: "集中配置带宽限制，按需应用到用户与规则。",
    group: "访问与管理",
    icon: Gauge,
    adminOnly: true,
  },
  {
    path: "/panel-sharing",
    title: "面板共享",
    description: "分享节点资源，接入其他面板的远程节点。",
    group: "访问与管理",
    icon: Share2,
    adminOnly: true,
  },
  {
    path: "/config",
    title: "系统设置",
    description: "管理全局配置、外观、公告与数据备份。",
    group: "系统",
    icon: Settings,
    adminOnly: true,
  },
  {
    path: "/profile",
    title: "个人中心",
    description: "查看账号信息并管理个人安全设置。",
    group: "系统",
    icon: UserRound,
  },
];
